path_to_source: "full_path_to_folder_with_howitzer_project"

# -- Capistrano settings
application: howitzer_stat
domain: localhost
user: deployer
deploy_to: /var/www/${application}

# -- Unicorn settings
worker_processes: 2
port: 80