path_to_source: "<Specify full path here to folder with test project code>"

# -- Capistrano settings
application: howitzer_stat
domain: localhost
user: deployer
deploy_to: /opt/www/${application}

# -- Unicorn settings
worker_processes: 2
port: 80